apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"

namespace: openshift-operators-redhat

resources:
  - namespace.yaml
  - elasticsearch-subscription.yaml
  - elasticsearch-operatorgroup.yaml
