kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - ../../../../../Applications/openshift-image-registry/block-storage/base

patches:
  - target:
      kind: Config
      name: cluster
    patch: |-
      - op: replace
        path: /spec/managementState
        value: 'Managed'
      - op: replace
        path: /spec/rolloutStrategy
        value: 'Recreate'
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/storage
        value: {pvc: {claim: 'image-registry-storage'}}
