apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../../Applications/openshift-logging/create-cluster-logging-instance/base

patches:
  - target:
      kind: ClusterLogging
      name: instance
    patch: |-
      - op: replace
        path: /spec/logStore/elasticsearch/storage/storageClassName
        value: 'cluster-logging'
      - op: replace
        path: /spec/logStore/elasticsearch/resources/limits/memory
        value: 8Gi
      - op: replace
        path: /spec/logStore/elasticsearch/resources/requests/memory
        value: 8Gi
