apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../../Applications/openshift-logging/create-cluster-logging-instance/base

patches:
  - target:
      kind: ClusterLogging
      name: instance
    patch: |-
      - op: remove
        path: /spec/logStore/elasticsearch/storage/storageClassName
      - op: replace
        path: /spec/logStore/elasticsearch/storage
        value: {}
      - op: replace
        path: /spec/logStore/elasticsearch/resources/limits/memory
        value: 5Gi
      - op: replace
        path: /spec/logStore/elasticsearch/resources/requests/memory
        value: 5Gi
