apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"

resources:
  - pvc.yaml
  - user-workload-monitoring-config.yaml
  - cluster-monitoring-config.yaml
