apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-etcd-backup
  labels:
    app: openshift-backup
rules:
  - apiGroups: ["*"]
    resources: 
       - "nodes" 
    verbs: ["get", "list"]
  - apiGroups: 
      - "*"
    resources: 
      - "*"
    verbs: 
      - "*"
