kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - ../../../../Applications/openshift-monitoring/base

configMapGenerator:
- name: cluster-monitoring-config
  namespace: openshift-monitoring
  files:
  - cluster-monitoring-config/config.yaml
  behavior: merge
- name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
  files:
  - user-workload-monitoring-config/config.yaml
  behavior: merge
