kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - ../../../../Applications/configure-kubelet/base

patches:
  - target:
      kind: KubeletConfig
      name: configure-kubeconfig
    patch: |-
      - op: remove
        path: /spec/kubeletConfig/podsPerCore
      - op: add
        path: /spec/machineConfigPoolSelector/matchLabels
        value: {custom-kubelet: small-pods}
  - target:
      kind: MachineConfigPool
      name: machine-config-pool
    patch: |-
      - op: replace
        path: /metadata/name
        value: custom-kubelet
      - op: add
        path: /spec/nodeSelector
        value: {matchLabels: {kubernetes.io/hostname: openshift-node.escbutton.com}}
      - op: add
        path: /metadata/labels
        value: {custom-kubelet: small-pods}
