apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../../../Applications/openshift-elasticsearch/operator/base

patchesJson6902:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: elasticsearch-operator
      namespace: openshift-operators-redhat
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'
  - target:
      kind: Namespace
      name: openshift-operators-redhat
    patch: |-
      - op: add
        path: /metadata/labels
        value: {openshift.io/cluster: "true"}
