---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../../../Applications/openshift-logging/operator/base

patches:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: cluster-logging
      namespace: openshift-logging
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'
  - target:
      kind: Namespace
      name: openshift-logging
    patch: |-
      - op: add
        path: /metadata/labels
        value: {openshift.io/cluster: "true"}
